<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-EK6AVS7" failures="1" tests="1" name="Test" time="0.036" errors="0" timestamp="2021-08-31T17:57:27 IST">
  <testcase classname="testcases.Sample" name="checkAssertion" time="0.008">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [2] but found [1]
at testcases.Sample.checkAssertion(Sample.java:13)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- checkAssertion -->
</testsuite> <!-- Test -->
